### ISSUE TITLE
Ideas for the Future :)

### ISSUE THREAD

**Issue by FormunaGit** [lavafroth/pwnpi-amora#2]
Here are some ideas I'd love to see in this:

1. Use adafruit's [DuckyScript library](https://docs.circuitpython.org/projects/ducky/en/latest/api.html) to use DuckyScript 2.0
2. Make the payload selections buttons (to change the mouse icon, gives a better feel)
3. Have a `docs` menu for people who wanna make scripts
4. H I L I G H T I N G
5. A custom command to let people type their own HID commands instead of the DuckyScript
Also PLEASE make a Discord or some way to contact you :pray:

**Comment by lavafroth** [comment]
Hey there, thank you for showing your interest in this project!

First, thank you for bringing the duckyscript library to my attention. I will definitely migrate the code to using the API very soon.

I also acknowledge that there are a few styling issues to be ironed out. I have also planned highlighting 😁. If you have other design improvements or different ideas, feel free to create a pull request.

Regarding the `docs`, I am hesitant about keeping documentation on the microcontroller itself. Sure, it gives a better experience overall but it might cut down the number of scripts one can store.

> A custom command to let people type their own HID commands instead of the DuckyScript

This is going to backlog for now.

I don't plan to use Discord. However, I will open GitHub discussions for this project for other ideas.
